build:
    nodes:
        my-node:
            services:
                redis: 4
    environment:
        variables:
            DB_HOST: '127.0.0.1'
            DB_NAME: 'rest_api_slim_php'
            DB_USER: 'root'
            DB_PASS: ''
            DB_PORT: '3306'
            SECRET_KEY: 'YourSuperSecret-KeY'
            REDIS_ENABLED: true
            REDIS_URL: 'localhost'
        php:
            version: 7.4
    project_setup:
        before:
            - mysql -e "CREATE DATABASE rest_api_slim_php"
            - mysql rest_api_slim_php < database/database.sql
        override:
            - php-scrutinizer-run
            -
                command: 'vendor/bin/phpunit --coverage-clover=clover.xml'
                coverage:
                    file: 'clover.xml'
                    format: 'clover'
